process.env.NEXT_PUBLIC_SUPABASE_URL='https://test.supabase.co'
process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY='test-key'
process.env.SUPABASE_URL='https://test.supabase.co'
process.env.SUPABASE_ANON_KEY='test-key'
process.env.OPENAI_API_KEY='test-key'